version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: "cloud-tech"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: cloud-tech:latest
    container_name: app
    build:
      context: .
    depends_on:
      - db
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_DATABASE=cloud-tech
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - JWT_SECRET=some_secret
    ports:
      - "4000:4000"
    command: ["./wait-for-it/wait-for-it.sh", "db:5432", "--", "npm",  "start"]