version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=50'
      - '-c'
      - 'shared_buffers=1GB'
      - '-c'
      - 'effective_cache_size=4GB'
      - '-c'
      - 'work_mem=16MB'
      - '-c'
      - 'maintenance_work_mem=512MB'
      - '-c'
      - 'random_page_cost=1.1'
      - '-c'
      - 'temp_file_limit=10GB'
      - '-c'
      - 'log_min_duration_statement=200ms'
      - '-c'
      - 'idle_in_transaction_session_timeout=10s'
      - '-c'
      - 'lock_timeout=1s'
      - '-c'
      - 'statement_timeout=60s'
      - '-c'
      - 'shared_preload_libraries=pg_stat_statements'
      - '-c'
      - 'pg_stat_statements.max=10000'
      - '-c'
      - 'pg_stat_statements.track=all'
    environment:
      POSTGRES_DB: 'cloud-tech'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d cloud-tech']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  api:
    image: back/cloud-tech-ts:latest
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    depends_on:
      - postgres
    environment:
      - APP_PORT=5000
      - SOCKET_PORT=4000
      - DB_HOST=postgres
      - DB_DATABASE=cloud-tech
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - JWT_SECRET=some_secret
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: ['./wait-for-it/wait-for-it.sh', 'postgres:5432', '--', 'npm', 'run', 'dev']

  postgres_exporter:
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter:v0.10.0
    environment:
      DATA_SOURCE_URI: 'postgres:5432/root?sslmode=disable'
      DATA_SOURCE_USER: 'root'
      DATA_SOURCE_PASS: 'root'
      PG_EXPORTER_EXTEND_QUERY_PATH: '/etc/postgres_exporter/queries.yaml'
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - '9187:9187'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
